# Generated by Django 2.2.4 on 2019-08-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190817_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='cards',
            field=models.ManyToManyField(blank=True, to='api.Card'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
