# Generated by Django 2.2.4 on 2019-08-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190818_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='collections',
            field=models.ManyToManyField(blank=True, to='api.Collection'),
        ),
    ]
