# Generated by Django 2.2.4 on 2019-08-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_card_collections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='collections',
        ),
        migrations.AlterField(
            model_name='collection',
            name='cards',
            field=models.ManyToManyField(blank=True, related_name='collections', to='api.Card'),
        ),
    ]
